### ISSUE TITLE
If there are 3 item, infinite not work.

### ISSUE THREAD

**Issue by jangsy7883** [gringoireDM/LNZCollectionLayouts#7] opened 2018-01-29 06:22 UTC
https://dl.dropboxusercontent.com/s/8ocdm3xrcdfqsoo/ScreenRecording.gif?dl=0

Check the link.

Can you solve this problem?

**Comment by gringoireDM** [comment] 2018-01-29 18:37
Hi, sure thing. can you provide me a sample project where the issue is reproducible so I can investigate this edge case? Thank you

**Comment by jangsy7883** [comment] 2018-01-30 00:29
[InfiniteCollectionVIewTest.zip](https://github.com/gringoireDM/LNZCollectionLayouts/files/1675787/InfiniteCollectionVIewTest.zip)

I created a simple sample project.

I hope this helps.

**Comment by gringoireDM** [comment] 2018-01-31 10:41
Perfect. Thank you. I will take a look at it in the weekend. When the items are not enough to make it infinite, usually the layout should fallback to a centred layout. I will investigate about why this is not happening.

**Comment by gringoireDM** [comment] 2018-01-31 11:54
I had the time to review your example now and I found out the issue. The infinite scroll will work in your particular case where the size of the cells are big enough to avoid each cell to be displayed twice on screen. I will open a PR soon with the bug fix. Thanks for the bug report, and have a nice day.

**Comment by gringoireDM** [comment] 2018-01-31 12:26
Issue resolved in #8 

pod update and it will be fine now

**Closed by gringoireDM** 2018-01-31 12:26 UTC
Labels: bug

**Comment by jangsy7883** [comment] 2018-02-01 01:23
I found that the issue was resolved.
It's great too. Thanks.
